// ============================================================================
//  Guerrilla Mode - the SYNTHETIC island boots (issue #56 task 7, #54 E1).
//    Guerrilla.UdIsland is the verbatim scaffold output for the repo's own
//    @udisland fixture (tests/fixtures/mods-island/@udisland, generated by
//    generate_udisland.py): a 3.2 km dome island with three named towns of
//    five house boxes each and a road net between them. Nothing in it is
//    Bohemia data. The scaffold ran against the config-only mini package, so
//    this boot on the Classic package is also the proof that a template
//    scaffolded without game data is a template the real engine accepts.
// ============================================================================
triSimUntil { GM_LIB_READY }
triSimUntil { alive player }
// -- the placeholder pair resolved through the global faction library -------
triAssertEq [(gmOccupierSide), "EAST"]
triAssertEq [(gmResistanceSide), "GUER"]
triAssertEq [(format ["%1", side player]), "GUER"]
// -- the scaffold's five zones came through the registry intact --------------
//    (3 towns, the camp, one outpost: the island is too small for more, and
//    the scaffold said so in its WARN lines)
triSimUntil { gmZoneCount >= 5 }
triAssertEq [(gmZoneCount), 5]
gsCamp = gmZoneIndex "Camp"
triAssertEq [((gmZone gsCamp) select 1), "CAMP"]
triAssertEq [((gmZone gsCamp) select 2), "GUER"]
gsOut = gmZoneIndex "Outpost 1"
triAssertEq [((gmZone gsOut) select 1), "OUTPOST"]
triAssertEq [((gmZone gsOut) select 2), "EAST"]
gsTown = gmZoneIndex "Northam"
triAssertEq [((gmZone gsTown) select 1), "CITY"]
triAssertEq [((gmZone gsTown) select 2), "NEUTRAL"]
// the sampled elevation is real dome ground (about 24 m), not the Names label size (100)
triAssertEq [((((gmZone gsTown) select 8) select 2) > 10) && ((((gmZone gsTown) select 8) select 2) < 60), true]
// -- the runtime saw the synthetic houses as Buildings: the town survived the
//    mission-time settlement probe (three Building objects over 4 m within
//    300 m), which is the whole reason the fixture ships house_a.p3d with a
//    class=house property and a House-derived config class ------------------
triAssertEq [(gmZoneIndex "Eastwick") >= 0, true]
triAssertEq [(gmZoneIndex "Southmere") >= 0, true]
// -- the player stands at the camp the scaffold placed, on dry land ---------
triAssertEq [(player distance ((gmZone gsCamp) select 8)) < 60, true]
triAssertEq [((getPos player) select 2) < 5, true]
triEndTest
