<#
.SYNOPSIS
    Installs the @LoBo Guerrilla war rosters into the mod's own bin\config.cpp.

.DESCRIPTION
    Since issue #54 A4 the eight @LoBo faction descriptors (IDF, EgyptFrontier,
    EgyptArmy, Syria, Jordan, Hizballah, PLO, PLO_East) live once in the tracked
    guerrilla-mode/config/lobo-factions.hpp. The Guerrilla island templates no
    longer declare them, so a player who mounts @LoBo needs that table to reach
    the merged CfgGuerrillaFactions somehow. This script gives it the home a
    player actually has: <@LoBo>\bin\config.cpp, the mod's deferred-merge
    config, which the engine layers onto Pars exactly like an addon config
    (issue #56 task 2).

    @LoBo is gitignored third-party data, so this is a REGENERATION step in the
    same family as the mod doctor: rerun it after reinstalling or updating
    @LoBo. The tracked artifact is this script plus the header it copies; the
    written config.cpp exists only on the machine that ran it.

    The lobo test lanes do not need it: tests/fixtures/mods-lobo/@lobofixup
    #includes the same header, so a lane that mounts the fixture carries the
    rosters either way, and a lane that mounts @LoBo alone needs this install.

.PARAMETER LoBoDir
    The @LoBo mod folder. Default: D:\Arma_CWA\@LoBo

.PARAMETER WhatIf
    Print what would be written and write nothing.
#>
param(
    [string]$LoBoDir = 'D:\Arma_CWA\@LoBo',
    [switch]$WhatIf
)
$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot '..\..\guerrilla-mode\config\lobo-factions.hpp'
$source = [System.IO.Path]::GetFullPath($source)
if (-not (Test-Path -LiteralPath $source)) { throw "roster header not found: $source" }
if (-not (Test-Path -LiteralPath $LoBoDir)) { throw "@LoBo folder not found: $LoBoDir" }

$binDir = Join-Path $LoBoDir 'bin'
$target = Join-Path $binDir 'config.cpp'

# A mod-level bin\config.cpp REPLACES a bin\config.bin for the config reader
# (ParseConfigFromDir tries config.cpp first). Stock @LoBo ships no config.bin
# in bin\ (the 2005 one sits in bin\configBackup), but say so if that changes.
$bin = Join-Path $binDir 'config.bin'
if (Test-Path -LiteralPath $bin) {
    Write-Warning "$bin exists and will be SHADOWED by config.cpp; merge its classes into the header first if they matter."
}

$header = Get-Content -LiteralPath $source -Raw
$stamp = (Get-Date).ToString('yyyy-MM-dd')
$banner = @"
// GENERATED by arma_CWR/tools/lobo/install-lobo-factions.ps1 on $stamp.
// Do not edit: the tracked source is arma_CWR/guerrilla-mode/config/lobo-factions.hpp.
// Rerun the script after reinstalling @LoBo.

"@
$content = $banner + $header

if ($WhatIf) {
    Write-Host "Would write $($content.Length) chars to $target"
    exit 0
}
if (-not (Test-Path -LiteralPath $binDir)) { New-Item -ItemType Directory -Path $binDir | Out-Null }
[System.IO.File]::WriteAllText($target, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Installed: $target ($($content.Length) chars, eight @LoBo rosters)"
exit 0
