// ============================================================================
//  PORTRAIT SHOOT - LOBO lane.  GENERATED by tools/screenshots/portrait_roster.py;
//  edit that script and re-emit, never this file.
//
//  WHAT THIS PRODUCES.  One capture per (unit class x face) pair, named
//  "<class>__<face>" in lowercase, which is exactly the key the dossier looks
//  up: GuerrillaJournalPages.cpp PortraitKeyOf builds
//  lower(bodyClass) + "__" + lower(face) and probes
//  gmcore\portraits\<key>.paa.  tools/screenshots/portrait_process.py turns
//  these PNGs into those .paa.
//
//  WHY THESE CLASSES.  They are the only bodies a Legend row can wear:
//  companionClass, companionClassCiv, the elite/tank commander body
//  (officer, else the top rung of tiers[]) and the sniper body (top rung of
//  tiersSniper[]).  Guards are never Legend rows.  23 classes x
//  4 faces = 92 captures.
//
//  WHY THE RIG IS FROZEN.  Four faces of one appearance have to be
//  interchangeable on the page, so every subject in this lane stands on ONE
//  anchor with ONE heading under ONE sky, one alive at a time, and the camera
//  never moves.  The background pixels are then literally the same image in
//  every frame, which portrait_process.py verifies by measuring a background
//  patch and refusing a lane whose patches drifted.
//      date      1985-06-15 10:30      anchor  [9060.0, 12180.0, 0]
//      setDir    120                   distance 3.5 m
//      overcast  0.25                  fog      0.05
//      camSetFov 0.3                  player parked at [9060.0, 9200.0, 0]
//
//  HARNESS RULES THIS FILE OBEYS (tools/screenshots/README.md):
//    * triScreenshot labels are BARE LOWERCASE STRING LITERALS.  A format[]
//      label desyncs the runner's own capture counter and the run dies on
//      FAIL:screenshot_not_written (integration.rs:790-795).
//    * Trident splits on newlines and on semicolons at brace depth 0 and
//      evaluates each statement separately, so nothing may be a _local.
//      Everything shared is a global (ss*).
//    * A scene change and its capture never share a statement.  triSimFrames
//      sits between them so the pose has settled.
//    * triCaptureAtPresent true, so each frame is captured at the swap, after
//      the gamma pass.  The default mid-frame capture is pre-gamma and darker
//      than what a player sees, which would calibrate the tone recipe on the
//      wrong pixels.
// ============================================================================

triSimUntil { alive player }

triCaptureAtPresent true

setDate [1985, 6, 15, 10, 30]
0 setOvercast 0.25
0 setFog 0.05
setViewDistance 1200
showCinemaBorder false

// Three kilometres away, and that is load-bearing.  A subject's HEAD tracks
// whatever it can see, and with the player parked 180 m off every calibration
// frame came back in hard profile.
player setCaptive true
player setPos [9060.0, 9200.0, 0]

// The four tokens this catalogue is built on, enumerated from the loaded
// package rather than assumed.  triListFaces filters CfgFaces down to the
// entries a MAN body can actually wear (no `disabled`, no `woman`, no
// "Custom"), so a token missing here would mean the file names a key the
// engine can never produce.
ssFaces = triListFaces
triAssert [("Face10" in ssFaces)]
triAssert [("Face18" in ssFaces)]
triAssert [("Face27" in ssFaces)]
triAssert [("Face33" in ssFaces)]

createCenter west
createCenter east
createCenter resistance
createCenter civilian
ssGrpW = createGroup west
ssGrpE = createGroup east
ssGrpG = createGroup resistance

// The cutscene camera exists only to suppress the HUD: World.cpp:1603 gates
// the HUD draw on `!_cameraEffect`.  Its own transform is irrelevant because
// triSetUnitFaceView pins the render camera, but its FOV is NOT - World.cpp:
// 906-919 takes fov from the active camera effect and the triSetView override
// at :1251-1254 replaces the transform only.  So this is the portrait lens -
// and camSetTarget has to come first or camSetFov is silently ignored.
ssCam = "camera" camCreate [9060.0, 12180.0, 30]
ssCam cameraEffect ["internal", "back"]
ssCam camSetTarget [9060.0, 12380.0, 30]
ssCam camSetFov 0.3
ssCam camCommit 0

// A long warm-up, and it is not padding.  The first run of this shoot came back
// with its first four frames measurably brighter than the other thirty-two: the
// sky is still settling to the requested date and overcast for the first second
// or so of a booted world, and portrait_process.py's lighting check refused the
// whole lane over it.  Two hundred frames is well past where the patch means go
// flat.
triSimFrames 200

// Spawn one subject at the anchor, pose him, and leave him standing.  ssU is
// the live body; ssMade says whether the class materialised at all (an
// unresolvable class is a no-show, not a crash, so the shoot skips it rather
// than dying 90 captures in).
ssMake = {
    ssU = objNull;
    ssBefore = count (units ssGrp);
    ssCls createUnit [[9060.0, 12180.0, 0], ssGrp, "", 0.4, "PRIVATE"];
    ssMade = count (units ssGrp) > ssBefore;
    if (ssMade) then { ssU = (units ssGrp) select (count (units ssGrp) - 1) }
}

// setSkill 0.1 rather than 0: a zero-skill unit's AI does not run at all and
// the engine logs "check failed: ability > 0" once a second for as long as it
// lives.  disableAI TARGET + doWatch keep the head square to the camera.
ssPose = {
    ssU setCaptive true;
    ssU disableAI "MOVE";
    ssU disableAI "AUTOTARGET";
    ssU disableAI "TARGET";
    ssU setBehaviour "CARELESS";
    ssU setSkill 0.1;
    ssU setDir 120;
    ssU setPos [9060.0, 12180.0, 0];
    ssU doWatch [9146.6, 12130.0, 1.6]
}

// Twice, with frames between: the first call is what forces EffectStandStill
// and the Default mimic (TriSetPersonFaceView), and the pose needs frames to
// settle before the camera is worth trusting.
ssFrame = {
    triSetUnitFaceView [ssU, 3.5];
    triSimFrames 6
}

// ---- ONE THROWAWAY SUBJECT, and it earns its place ----
// The first capture taken on the pinned portrait view comes back PRE-GAMMA even
// with triCaptureAtPresent on: its background patch measures 138.6 where every
// later frame measures 153.6, and 255*(138.6/255)^(1/1.2) = 152.8 - the 1.2
// gamma pass, missing, on all three channels to within 0.2/255.  Every frame
// after it is correct.  So the shoot burns one full block, identical to the
// real ones, before it starts.  portrait_process.py drops any capture whose
// label carries no "__", which is what keeps this frame out of the catalogue.

// ---- LoBoGolaniWB / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "warmup_discard"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWB / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwb__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWB / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWB"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwb__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWB / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWB"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwb__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWB / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWB"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwb__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWBo / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWBo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWBo"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwbo__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWBo / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWBo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWBo"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwbo__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWBo / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWBo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWBo"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwbo__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoGolaniWBo / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBoGolaniWBo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoGolaniWBo"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobogolaniwbo__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoShayetetSN / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBoShayetetSN"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoShayetetSN"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "loboshayetetsn__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoShayetetSN / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBoShayetetSN"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoShayetetSN"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "loboshayetetsn__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoShayetetSN / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBoShayetetSN"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoShayetetSN"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "loboshayetetsn__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBoShayetetSN / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBoShayetetSN"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBoShayetetSN"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "loboshayetetsn__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrp / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrp"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrp"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrp__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrp / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrp"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrp"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrp__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrp / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrp"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrp"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrp__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrp / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrp"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrp"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrp__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01E / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01E"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01e__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01E / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01E"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01e__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01E / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01E"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01e__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01E / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01E"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01e__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrpo / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrpo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrpo"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrpo__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrpo / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrpo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrpo"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrpo__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrpo / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrpo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrpo"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrpo__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_FrtCrpo / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_FrtCrpo"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_FrtCrpo"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_frtcrpo__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_Grdsnip / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_Grdsnip"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_Grdsnip"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_grdsnip__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_Grdsnip / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_Grdsnip"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_Grdsnip"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_grdsnip__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_Grdsnip / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_Grdsnip"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_Grdsnip"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_grdsnip__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_Grdsnip / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_Grdsnip"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_Grdsnip"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_grdsnip__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantry / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantry"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantry"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantry__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantry / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantry"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantry"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantry__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantry / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantry"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantry"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantry__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantry / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantry"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantry"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantry__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantryO / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantryO"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantryO"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantryo__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantryO / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantryO"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantryO"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantryo__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantryO / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantryO"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantryO"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantryo__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_infantryO / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_infantryO"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_infantryO"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_infantryo__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_SFsnip2 / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_SFsnip2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_SFsnip2"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_sfsnip2__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_SFsnip2 / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_SFsnip2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_SFsnip2"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_sfsnip2__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_SFsnip2 / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_SFsnip2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_SFsnip2"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_sfsnip2__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Egypt_SFsnip2 / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Egypt_SFsnip2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Egypt_SFsnip2"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_egypt_sfsnip2__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_Syria / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_Syria"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_Syria"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syria__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_Syria / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_Syria"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_Syria"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syria__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_Syria / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_Syria"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_Syria"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syria__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_Syria / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_Syria"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_Syria"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syria__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_SyriaO2 / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_SyriaO2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_SyriaO2"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syriao2__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_SyriaO2 / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_SyriaO2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_SyriaO2"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syriao2__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_SyriaO2 / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_SyriaO2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_SyriaO2"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syriao2__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Liz_Infantry_SyriaO2 / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Liz_Infantry_SyriaO2"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Liz_Infantry_SyriaO2"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_liz_infantry_syriao2__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D_off / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D_off"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D_off"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d_off__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D_off / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D_off"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D_off"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d_off__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D_off / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D_off"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D_off"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d_off__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_inf_jor_D_off / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_inf_jor_D_off"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_inf_jor_D_off"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_inf_jor_d_off__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_sniper_jor / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_sniper_jor"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_sniper_jor"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_sniper_jor__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_sniper_jor / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_sniper_jor"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_sniper_jor"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_sniper_jor__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_sniper_jor / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_sniper_jor"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_sniper_jor"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_sniper_jor__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_sniper_jor / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_sniper_jor"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_sniper_jor"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_sniper_jor__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahRifle4 / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahRifle4"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahRifle4"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahrifle4__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahRifle4 / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahRifle4"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahRifle4"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahrifle4__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahRifle4 / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahRifle4"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahRifle4"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahrifle4__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahRifle4 / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahRifle4"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahRifle4"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahrifle4__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahLeader / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahLeader"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahLeader"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahleader__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahLeader / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahLeader"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahLeader"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahleader__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahLeader / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahLeader"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahLeader"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahleader__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahLeader / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahLeader"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahLeader"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahleader__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahSniper1 / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahSniper1"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahSniper1"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahsniper1__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahSniper1 / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahSniper1"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahSniper1"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahsniper1__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahSniper1 / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahSniper1"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahSniper1"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahsniper1__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_HizballahSniper1 / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_HizballahSniper1"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_HizballahSniper1"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_hizballahsniper1__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01R / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01R"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01r__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01R / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01R"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01r__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01R / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01R"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01r__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_01R / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_01R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_01R"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_01r__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03R / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03R"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03r__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03R / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03R"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03r__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03R / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03R"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03r__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03R / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03R"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03R"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03r__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDR / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDR"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDR"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svdr__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDR / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDR"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDR"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svdr__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDR / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDR"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDR"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svdr__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDR / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDR"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDR"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svdr__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03E / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03E"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03e__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03E / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03E"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03e__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03E / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03E"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03e__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_03E / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_03E"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_03E"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_03e__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDE / Face10 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDE"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svde__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDE / Face18 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDE"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svde__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDE / Face27 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDE"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svde__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- LoBo_Terror_SVDE / Face33 ----
ssGrp = ssGrpG
ssCls = "LoBo_Terror_SVDE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "LoBo_Terror_SVDE"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "lobo_terror_svde__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

triEndTest
