// ============================================================================
//  PORTRAIT SHOOT - VANILLA lane.  GENERATED by tools/screenshots/portrait_roster.py;
//  edit that script and re-emit, never this file.
//
//  WHAT THIS PRODUCES.  One capture per (unit class x face) pair, named
//  "<class>__<face>" in lowercase, which is exactly the key the dossier looks
//  up: GuerrillaJournalPages.cpp PortraitKeyOf builds
//  lower(bodyClass) + "__" + lower(face) and probes
//  gmcore\portraits\<key>.paa.  tools/screenshots/portrait_process.py turns
//  these PNGs into those .paa.
//
//  WHY THESE CLASSES.  They are the only bodies a Legend row can wear:
//  companionClass, companionClassCiv, the elite/tank commander body
//  (officer, else the top rung of tiers[]) and the sniper body (top rung of
//  tiersSniper[]).  Guards are never Legend rows.  9 classes x
//  4 faces = 36 captures.
//
//  WHY THE RIG IS FROZEN.  Four faces of one appearance have to be
//  interchangeable on the page, so every subject in this lane stands on ONE
//  anchor with ONE heading under ONE sky, one alive at a time, and the camera
//  never moves.  The background pixels are then literally the same image in
//  every frame, which portrait_process.py verifies by measuring a background
//  patch and refusing a lane whose patches drifted.
//      date      1985-06-15 10:30      anchor  [3892.7, 6980.0, 0]
//      setDir    120                   distance 3.5 m
//      overcast  0.25                  fog      0.05
//      camSetFov 0.3                  player parked at [3892.7, 4000.0, 0]
//
//  HARNESS RULES THIS FILE OBEYS (tools/screenshots/README.md):
//    * triScreenshot labels are BARE LOWERCASE STRING LITERALS.  A format[]
//      label desyncs the runner's own capture counter and the run dies on
//      FAIL:screenshot_not_written (integration.rs:790-795).
//    * Trident splits on newlines and on semicolons at brace depth 0 and
//      evaluates each statement separately, so nothing may be a _local.
//      Everything shared is a global (ss*).
//    * A scene change and its capture never share a statement.  triSimFrames
//      sits between them so the pose has settled.
//    * triCaptureAtPresent true, so each frame is captured at the swap, after
//      the gamma pass.  The default mid-frame capture is pre-gamma and darker
//      than what a player sees, which would calibrate the tone recipe on the
//      wrong pixels.
// ============================================================================

triSimUntil { alive player }

triCaptureAtPresent true

setDate [1985, 6, 15, 10, 30]
0 setOvercast 0.25
0 setFog 0.05
setViewDistance 1200
showCinemaBorder false

// Three kilometres away, and that is load-bearing.  A subject's HEAD tracks
// whatever it can see, and with the player parked 180 m off every calibration
// frame came back in hard profile.
player setCaptive true
player setPos [3892.7, 4000.0, 0]

// The four tokens this catalogue is built on, enumerated from the loaded
// package rather than assumed.  triListFaces filters CfgFaces down to the
// entries a MAN body can actually wear (no `disabled`, no `woman`, no
// "Custom"), so a token missing here would mean the file names a key the
// engine can never produce.
ssFaces = triListFaces
triAssert [("Face10" in ssFaces)]
triAssert [("Face18" in ssFaces)]
triAssert [("Face27" in ssFaces)]
triAssert [("Face33" in ssFaces)]

createCenter west
createCenter east
createCenter resistance
createCenter civilian
ssGrpW = createGroup west
ssGrpE = createGroup east
ssGrpG = createGroup resistance

// The cutscene camera exists only to suppress the HUD: World.cpp:1603 gates
// the HUD draw on `!_cameraEffect`.  Its own transform is irrelevant because
// triSetUnitFaceView pins the render camera, but its FOV is NOT - World.cpp:
// 906-919 takes fov from the active camera effect and the triSetView override
// at :1251-1254 replaces the transform only.  So this is the portrait lens -
// and camSetTarget has to come first or camSetFov is silently ignored.
ssCam = "camera" camCreate [3892.7, 6980.0, 30]
ssCam cameraEffect ["internal", "back"]
ssCam camSetTarget [3892.7, 7180.0, 30]
ssCam camSetFov 0.3
ssCam camCommit 0

// A long warm-up, and it is not padding.  The first run of this shoot came back
// with its first four frames measurably brighter than the other thirty-two: the
// sky is still settling to the requested date and overcast for the first second
// or so of a booted world, and portrait_process.py's lighting check refused the
// whole lane over it.  Two hundred frames is well past where the patch means go
// flat.
triSimFrames 200

// Spawn one subject at the anchor, pose him, and leave him standing.  ssU is
// the live body; ssMade says whether the class materialised at all (an
// unresolvable class is a no-show, not a crash, so the shoot skips it rather
// than dying 90 captures in).
ssMake = {
    ssU = objNull;
    ssBefore = count (units ssGrp);
    ssCls createUnit [[3892.7, 6980.0, 0], ssGrp, "", 0.4, "PRIVATE"];
    ssMade = count (units ssGrp) > ssBefore;
    if (ssMade) then { ssU = (units ssGrp) select (count (units ssGrp) - 1) }
}

// setSkill 0.1 rather than 0: a zero-skill unit's AI does not run at all and
// the engine logs "check failed: ability > 0" once a second for as long as it
// lives.  disableAI TARGET + doWatch keep the head square to the camera.
ssPose = {
    ssU setCaptive true;
    ssU disableAI "MOVE";
    ssU disableAI "AUTOTARGET";
    ssU disableAI "TARGET";
    ssU setBehaviour "CARELESS";
    ssU setSkill 0.1;
    ssU setDir 120;
    ssU setPos [3892.7, 6980.0, 0];
    ssU doWatch [3979.3, 6930.0, 1.6]
}

// Twice, with frames between: the first call is what forces EffectStandStill
// and the Default mimic (TriSetPersonFaceView), and the pose needs frames to
// settle before the camera is worth trusting.
ssFrame = {
    triSetUnitFaceView [ssU, 3.5];
    triSimFrames 6
}

// ---- ONE THROWAWAY SUBJECT, and it earns its place ----
// The first capture taken on the pinned portrait view comes back PRE-GAMMA even
// with triCaptureAtPresent on: its background patch measures 138.6 where every
// later frame measures 153.6, and 255*(138.6/255)^(1/1.2) = 152.8 - the 1.2
// gamma pass, missing, on all three channels to within 0.2/255.  Every frame
// after it is correct.  So the shoot burns one full block, identical to the
// real ones, before it starts.  portrait_process.py drops any capture whose
// label carries no "__", which is what keeps this frame out of the catalogue.

// ---- SoldierWB / Face10 ----
ssGrp = ssGrpW
ssCls = "SoldierWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "warmup_discard"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWB / Face10 ----
ssGrp = ssGrpW
ssCls = "SoldierWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwb__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWB / Face18 ----
ssGrp = ssGrpW
ssCls = "SoldierWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWB"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwb__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWB / Face27 ----
ssGrp = ssGrpW
ssCls = "SoldierWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWB"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwb__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWB / Face33 ----
ssGrp = ssGrpW
ssCls = "SoldierWB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWB"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwb__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerW / Face10 ----
ssGrp = ssGrpW
ssCls = "OfficerW"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerW"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerw__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerW / Face18 ----
ssGrp = ssGrpW
ssCls = "OfficerW"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerW"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerw__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerW / Face27 ----
ssGrp = ssGrpW
ssCls = "OfficerW"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerW"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerw__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerW / Face33 ----
ssGrp = ssGrpW
ssCls = "OfficerW"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerW"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerw__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWSniper / Face10 ----
ssGrp = ssGrpW
ssCls = "SoldierWSniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWSniper"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwsniper__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWSniper / Face18 ----
ssGrp = ssGrpW
ssCls = "SoldierWSniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWSniper"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwsniper__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWSniper / Face27 ----
ssGrp = ssGrpW
ssCls = "SoldierWSniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWSniper"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwsniper__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierWSniper / Face33 ----
ssGrp = ssGrpW
ssCls = "SoldierWSniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierWSniper"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldierwsniper__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierEB / Face10 ----
ssGrp = ssGrpE
ssCls = "SoldierEB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierEB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiereb__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierEB / Face18 ----
ssGrp = ssGrpE
ssCls = "SoldierEB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierEB"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiereb__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierEB / Face27 ----
ssGrp = ssGrpE
ssCls = "SoldierEB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierEB"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiereb__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierEB / Face33 ----
ssGrp = ssGrpE
ssCls = "SoldierEB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierEB"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiereb__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerE / Face10 ----
ssGrp = ssGrpE
ssCls = "OfficerE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerE"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officere__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerE / Face18 ----
ssGrp = ssGrpE
ssCls = "OfficerE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerE"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officere__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerE / Face27 ----
ssGrp = ssGrpE
ssCls = "OfficerE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerE"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officere__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerE / Face33 ----
ssGrp = ssGrpE
ssCls = "OfficerE"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerE"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officere__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierESniper / Face10 ----
ssGrp = ssGrpE
ssCls = "SoldierESniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierESniper"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldieresniper__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierESniper / Face18 ----
ssGrp = ssGrpE
ssCls = "SoldierESniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierESniper"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldieresniper__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierESniper / Face27 ----
ssGrp = ssGrpE
ssCls = "SoldierESniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierESniper"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldieresniper__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierESniper / Face33 ----
ssGrp = ssGrpE
ssCls = "SoldierESniper"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierESniper"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldieresniper__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGB / Face10 ----
ssGrp = ssGrpG
ssCls = "SoldierGB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGB"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergb__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGB / Face18 ----
ssGrp = ssGrpG
ssCls = "SoldierGB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGB"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergb__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGB / Face27 ----
ssGrp = ssGrpG
ssCls = "SoldierGB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGB"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergb__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGB / Face33 ----
ssGrp = ssGrpG
ssCls = "SoldierGB"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGB"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergb__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGFakeC / Face10 ----
ssGrp = ssGrpG
ssCls = "SoldierGFakeC"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGFakeC"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergfakec__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGFakeC / Face18 ----
ssGrp = ssGrpG
ssCls = "SoldierGFakeC"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGFakeC"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergfakec__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGFakeC / Face27 ----
ssGrp = ssGrpG
ssCls = "SoldierGFakeC"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGFakeC"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergfakec__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- SoldierGFakeC / Face33 ----
ssGrp = ssGrpG
ssCls = "SoldierGFakeC"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "SoldierGFakeC"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "soldiergfakec__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerG / Face10 ----
ssGrp = ssGrpG
ssCls = "OfficerG"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerG"] }
if (ssMade) then { ssU setFace "Face10" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerg__face10"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerG / Face18 ----
ssGrp = ssGrpG
ssCls = "OfficerG"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerG"] }
if (ssMade) then { ssU setFace "Face18" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerg__face18"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerG / Face27 ----
ssGrp = ssGrpG
ssCls = "OfficerG"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerG"] }
if (ssMade) then { ssU setFace "Face27" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerg__face27"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

// ---- OfficerG / Face33 ----
ssGrp = ssGrpG
ssCls = "OfficerG"
call ssMake
if (ssMade) then { call ssPose }
if (ssMade) then { triAssertEq [(typeOf ssU), "OfficerG"] }
if (ssMade) then { ssU setFace "Face33" }
triSimFrames 8
if (ssMade) then { triAssertNe [(triFaceTexture ssU), ""] }
if (ssMade) then { call ssFrame }
if (ssMade) then { call ssFrame }
triSimFrames 4
triScreenshot "officerg__face33"
if (ssMade) then { deleteVehicle ssU }
triSimFrames 4

triEndTest
